# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180920_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_photo',
            field=models.ImageField(default='imgages/infortx.png', upload_to=''),
        ),
    ]
