# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180923_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('SKUID', models.URLField(verbose_name='商品SKUID')),
                ('photo_url', models.URLField(verbose_name='图片地址')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
