# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('classify_name', models.CharField(max_length=50, verbose_name='分类名')),
                ('classify_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类简介')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('photo_url', models.ImageField(upload_to='photo_album/%Y%m/%d', verbose_name='图片地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('sku_name', models.CharField(max_length=255, verbose_name='商品sku名')),
                ('goods_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格')),
                ('repertory', models.IntegerField(default=0, verbose_name='库存')),
                ('Sales', models.IntegerField(default=0, verbose_name='销量')),
                ('logo', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='LOGO地址')),
                ('is_on_sale', models.BooleanField(choices=[((0, '下架'), (1, '上架'))], default=0, verbose_name='是否上架')),
                ('goods_calssify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsClassify', verbose_name='商品分类')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsSpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('spu_name', models.CharField(max_length=255, verbose_name='商品spu名称')),
                ('info', models.CharField(max_length=255, verbose_name='spu详情')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('unit_name', models.CharField(max_length=50, verbose_name='单位名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='SKUID',
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='photo_url',
            field=models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSpu', verbose_name='商品spu_id'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Units', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='goodsphoto',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSpu', verbose_name='商品spu'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='goods_sku',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSku', verbose_name='SKU商品'),
            preserve_default=False,
        ),
    ]
