# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20180924_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsclassify',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='goodsphoto',
            options={'verbose_name': '商品相册', 'verbose_name_plural': '商品相册'},
        ),
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品SKU表', 'verbose_name_plural': '商品SKU表'},
        ),
        migrations.AlterModelOptions(
            name='goodsspu',
            options={'verbose_name': '商品SPU表', 'verbose_name_plural': '商品SPU表'},
        ),
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': '商品单位', 'verbose_name_plural': '商品单位'},
        ),
        migrations.AlterField(
            model_name='goodsclassify',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='goodsphoto',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='goodsspu',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='units',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
    ]
