# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20180925_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsphoto',
            name='goods_spu',
        ),
        migrations.AddField(
            model_name='goodsphoto',
            name='goods_sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSku', verbose_name='商品sku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSku', verbose_name='商品spu_id'),
        ),
    ]
