# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20180925_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='goods_calssify',
        ),
        migrations.RemoveField(
            model_name='goodssku',
            name='goods_spu',
        ),
        migrations.RemoveField(
            model_name='goodssku',
            name='is_on_sale',
        ),
    ]
