# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_auto_20180925_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='is_on_sale',
            field=models.BooleanField(choices=[((0, '下架'), (1, '上架'))], default=0, verbose_name='是否上架'),
        ),
    ]
