# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_goodssku_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='goods_calssify',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsClassify', verbose_name='商品分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goods_spu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSpu', verbose_name='商品spu_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_on_sale',
            field=models.BooleanField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='是否上架'),
        ),
    ]
