# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0008_auto_20180925_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='goods_info',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='goodsspu',
            name='info',
            field=models.TextField(verbose_name='spu详情'),
        ),
    ]
