# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 14:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0009_auto_20180925_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=255, verbose_name='活动专区名称')),
                ('describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('Activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Activity', verbose_name='专区id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='goodsspu',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='spu详情'),
        ),
        migrations.AddField(
            model_name='activitygoods',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSku', verbose_name='商品sku'),
        ),
    ]
